version: '3'

services:
  librasysapi:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_DATABASE=creator-website
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
